# Generated by Django 4.2 on 2025-06-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this setting",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
