# Generated by Django 4.2 on 2025-06-16 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_managers_auditlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="User's department",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.department",
            ),
        ),
    ]
