# Generated by Django 4.2 on 2025-06-15 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0002_useractivitylog_reporttemplate_performancemetrics_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticssnapshot",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
