# Generated by Django 4.2 on 2025-06-15 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISentimentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "sentiment_score",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Sentiment score from -1.0 (negative) to 1.0 (positive)",
                        max_digits=4,
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Confidence of the sentiment analysis from 0.0 to 1.0",
                        max_digits=4,
                    ),
                ),
                (
                    "detected_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords detected that influenced the sentiment",
                    ),
                ),
                (
                    "analysis_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Other metadata from the analysis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Sentiment Analysis",
                "verbose_name_plural": "AI Sentiment Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aisentimentanalysis",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="ai_features_content_0e791e_idx",
            ),
        ),
    ]
