# Generated by Django 4.2 on 2025-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisentimentanalysis",
            name="detected_issues",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Potential issues detected, e.g., 'vague_language', 'bias_risk'",
            ),
        ),
    ]
